### ISSUE TITLE
Multi-line string issues with inputs

### ISSUE THREAD

**Issue by lakkeger** [localstack/setup-localstack#21]
# Issue Description
The parsed JSONs the action creates for the sub-modules are not substituted/parsed properly and dropping new line characters. Hence runs are failing with such input especially if the new lines are not just for cosmetics ie in the case of `preview-cmd`.
Additionally `"` characters are causing issues.

# How to reproduce
```yaml
- name: Deploy Preview
        uses: LocalStack/setup-localstack@v0.2.0
        env:
          LOCALSTACK_API_KEY: ${{ secrets.LOCALSTACK_API_KEY }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          state-backend: ephemeral
          state-action: start
          include-preview: 'true'
          install-awslocal: 'true'
          # Multi line commands are folding for some reason, so we enforce new lines
          # For more predictable usage, use script files
          preview-cmd: |
            npm install -g aws-cdk-local aws-cdk
            echo "HelloWorld"
```
# Output
<img width="1024" alt="image" src="https://github.com/localstack/setup-localstack/assets/43646571/24373597-85ae-4a55-bf9b-0253837ada80">

# Proposed Solution
Use `toJSON` with every parameter in the JSON inputs.
