### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement localstack-ext==4.0.3 (from localstack)

### ISSUE THREAD

**Issue by Joshlo** [localstack/setup-localstack#44]
Hi,

My pipeline worked last week, but now it's stopped and I'm getting the following error:

ERROR: Could not find a version that satisfies the requirement localstack-ext==4.0.3 (from localstack)

My setup is as following

```
jobs:
  test-and-lint:
    permissions:
      # Required to checkout the code
      contents: read
      # Required to put a comment into the pull-request
      pull-requests: write
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: smtdata/gh-actions/node-setup@v2
        with:
          node-version: 18

      - name: 'Sql server'
        uses: potatoqualitee/mssqlsuite@v1.7
        with:
          install: sqlengine
          sa-password: YourStrong!Passw0rd
          version: 2022

      - name: 'Run sql init'
        run: 'sqlcmd -S localhost -U sa -P YourStrong!Passw0rd -i .docker/database-setup.sql'

      - name: Start LocalStack
        uses: LocalStack/setup-localstack@v0.2.2
        with:
          image-tag: '3.4.0'
          install-awslocal: 'true'

      - name: Configure LocalStack
        shell: bash
        run: |
          bash .docker/localstack-setup.sh
```

Anything I can change in my setup that will make it work again?

**Comment by HarshCasper** [comment]
Hi @Joshlo — Thanks for sharing this issue. We'll look and figure out how to fix the problem for you. In the meantime, can you please share the full LocalStack logs as well?

**Comment by HarshCasper** [comment]
Hi @Joshlo — I was able to fix your issue. Here is a minimal GitHub Actions config that works in a similar fashion as your workflow:

```yaml
name: 'Check'
on:
  push:
    branches:
      - main
jobs:
  localstack:
    permissions: write-all
    name: Setup LocalStack Preview
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Start LocalStack
        uses: LocalStack/setup-localstack@v0.2.2
        with:
          image-tag: '3.4.0'
          install-awslocal: 'true'

      - name: Run awslocal commands
        run: |
          awslocal s3 mb s3://test
```

The only change you would require is adding this snippet to your workflow:

```
- uses: actions/setup-python@v5
  with:
    python-version: '3.10'
```

Let me know if that works for you! We're happy to help 🤗
