### ISSUE TITLE
Speeding up the runtime

### ISSUE THREAD

**Issue by sondrelg** [localstack/setup-localstack#49]
Hi!

Thanks for creating this project. Localstack has been very helpful in testing SQS/SNS locally! I'm currently on the non-pro version.

I just have one issue: in CI it takes over a minute to set up localstack for testing. Is there any way to speed this up? Here's a dump:

```
localstack/setup-localstack@v0.2.3
  with:
    image-tag: latest
    install-awslocal: true
    use-pro: false
    skip-startup: false
    skip-wait: false
    skip-ephemeral-stop: true
    state-backend: cloud-pods
    lifetime: 30
```

Would it, e.g., save time to skip installing the awslocal-cli and instead use the aws-cli with `--endpoint localhost:4566`? Are there other tricks like this you know of?
